import './scss/styles.scss';
import { EventEmitter } from "./components/base/Events";
import { ProductCatalog } from "./components/models/ProductCatalog";
import { Api } from "./components/base/Api";
import { API_URL } from "./utils/constants";
import { ServerApi } from "./components/communication/ServerApi";
import { IOrderResultApi, IProduct, TOrderResponse } from "./types";
import { cloneTemplate, ensureElement } from "./utils/utils";
import { CardBasket } from "./components/views/Card/CardBasket";
import { Buyer } from "./components/models/Buyer";
